### ISSUE TITLE
Using MapPath as item template

### ISSUE THREAD

**Issue by varadero** [ClemensFischer/XAML-Map-Control#73]
I am trying to show multiple circles in the MapControl instead of only one (as in the official sample app). I have added DataTemplate with `<map:MapPath ...` content copy/pasted from the same MainWindow.xaml and I am referencing this DataTemplate for each Polyline item:

```
...
        <DataTemplate x:Key="EllipseItemTemplate">
           <map:MapPath Location="53.5,8.2" Stroke="Blue" StrokeThickness="3" Fill="#1F007F00">
                <map:MapPath.Data>
                    <EllipseGeometry RadiusX="1852" RadiusY="1852"/>
                </map:MapPath.Data>
            </map:MapPath>
        </DataTemplate>
...
            <map:MapItemsControl ItemsSource="{Binding Polylines}"
                                 ItemTemplate="{StaticResource EllipseItemTemplate}"/>
```

I am receiving XAML designer and also runtime error:
```
Cannot set a property on object 'System.Windows.Media.EllipseGeometry' because it is in a read-only state.
Call stack:
 at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, Uri baseUri)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
   at System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
   at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MapControl.MapPanel.MeasureOverride(Size availableSize) in C:\dev\XAML-Map-Control\MapControl\Shared\MapPanel.cs:line 189
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.VisualTree.DispatcherVisualTreeContext.UpdateLayout()
   at Microsoft.VisualStudio.XSurface.Wpf.DesignerTapInstanceManager.AfterProcessActions(TapInstanceBuilderContext context)
```

My goal is to have multiple rectangles Locations (left-top and right-bottom) which will be part of the view model and render all of the rectangles on the map. Should I abandon `MapPath` and use something else ?

**Comment by ClemensFischer** [comment]
Use a regular Path element instead of MapPath, and set the Location property of the MapItem in an ItemContainerStyle, e.g. as in the PointItemStyle in the sample application.
